const lines = (...ls: string[]): string => ls.join('\r\n') + '\r\n';

export const SIMPLE_EVENT = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VEVENT',
	'UID:simple-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DTSTART;TZID=Europe/Paris:20260815T140000',
	'DTEND;TZID=Europe/Paris:20260815T150000',
	'SUMMARY:Team meeting',
	'DESCRIPTION:Quarterly review',
	'LOCATION:Room 4',
	'STATUS:CONFIRMED',
	'END:VEVENT',
	'END:VCALENDAR',
);

export const ALL_DAY_EVENT = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VEVENT',
	'UID:allday-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DTSTART;VALUE=DATE:20260820',
	'DTEND;VALUE=DATE:20260821',
	'SUMMARY:Company holiday',
	'END:VEVENT',
	'END:VCALENDAR',
);

export const RECURRING_WITH_OVERRIDE = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VEVENT',
	'UID:rec-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DTSTART;TZID=Europe/Paris:20260803T090000',
	'DTEND;TZID=Europe/Paris:20260803T093000',
	'RRULE:FREQ=WEEKLY;BYDAY=MO',
	'EXDATE;TZID=Europe/Paris:20260817T090000',
	'SUMMARY:Weekly standup',
	'END:VEVENT',
	'BEGIN:VEVENT',
	'UID:rec-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'RECURRENCE-ID;TZID=Europe/Paris:20260810T090000',
	'DTSTART;TZID=Europe/Paris:20260810T100000',
	'DTEND;TZID=Europe/Paris:20260810T103000',
	'SUMMARY:Weekly standup (moved)',
	'END:VEVENT',
	'END:VCALENDAR',
);

export const RICH_EVENT = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VEVENT',
	'UID:rich-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DTSTART:20260901T100000Z',
	'DTEND:20260901T110000Z',
	'SUMMARY:Project kickoff with a very long summary line that should be fold',
	' ed across lines by the generator',
	'ORGANIZER;CN=Alice:mailto:alice@example.com',
	'ATTENDEE;CN=Bob;ROLE=REQ-PARTICIPANT;PARTSTAT=ACCEPTED;RSVP=TRUE:mailto:bo',
	' b@example.com',
	'ATTENDEE;CN=Carol;PARTSTAT=NEEDS-ACTION:mailto:carol@example.com',
	'CATEGORIES:work,planning',
	'TRANSP:OPAQUE',
	'URL:https://example.com/kickoff',
	'X-CUSTOM-TAG:keep-me',
	'BEGIN:VALARM',
	'ACTION:DISPLAY',
	'TRIGGER:-PT15M',
	'DESCRIPTION:Reminder',
	'END:VALARM',
	'BEGIN:VALARM',
	'ACTION:EMAIL',
	'TRIGGER:-PT1H',
	'DESCRIPTION:Email reminder',
	'END:VALARM',
	'END:VEVENT',
	'END:VCALENDAR',
);

export const NO_DTEND_EVENT = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VEVENT',
	'UID:nodtend-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DTSTART:20260901T100000Z',
	'SUMMARY:Open-ended reminder',
	'END:VEVENT',
	'END:VCALENDAR',
);

export const SIMPLE_TODO = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'BEGIN:VTODO',
	'UID:todo-1@example.com',
	'DTSTAMP:20260801T120000Z',
	'DUE;TZID=Europe/Paris:20260830T180000',
	'SUMMARY:Write report',
	'DESCRIPTION:Final draft',
	'PRIORITY:1',
	'STATUS:IN-PROCESS',
	'PERCENT-COMPLETE:40',
	'CATEGORIES:work',
	'RELATED-TO:project-9@example.com',
	'END:VTODO',
	'END:VCALENDAR',
);

export const EMPTY_CALENDAR = lines(
	'BEGIN:VCALENDAR',
	'VERSION:2.0',
	'PRODID:-//Test//EN',
	'END:VCALENDAR',
);
